"""Aggregate results/v2/runs.jsonl into results/v2/summary.md and figures/v2/*.png."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import cv2
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from src.optics import DESCRIPTIONS, WATER_TYPES, Sensor, Water, degrade_image, effective_coefficients

ROOT = Path(__file__).resolve().parent
RES = ROOT / "results" / "v2"
FIG = ROOT / "figures" / "v2"
ORDER = ["clear", *WATER_TYPES]
N_IMAGES = 30


def load():
    return [json.loads(l) for l in (RES / "runs.jsonl").read_text().splitlines() if l.strip()]


def group(runs, **filt):
    g = defaultdict(list)
    for r in runs:
        if all(r.get(k) == v for k, v in filt.items()):
            g[r["water_type"]].append(r)
    return g


def stat(rs, key):
    v = np.array([r.get(key) if r.get(key) is not None else np.nan for r in rs], float)
    return np.nanmean(v) if np.isfinite(v).any() else np.nan, np.nanmin(v) if np.isfinite(v).any() else np.nan, \
        np.nanmax(v) if np.isfinite(v).any() else np.nan


def fmt(rs, key, digits=0, scale=1.0):
    m, lo, hi = (v * scale for v in stat(rs, key))
    if np.isnan(m):
        return "n/a"
    f = f"{{:.{digits}f}}"
    return f.format(m) if len(rs) == 1 or lo == hi else f"{f.format(m)} ({f.format(lo)}–{f.format(hi)})"


def table(rows_by_type, title, extra=""):
    out = [f"### {title}", "", *( [extra, ""] if extra else [] ),
           "| Water | n | Largest model /30 | Any model /30 | Sub-models | Accurate poses /30 | ATE RMSE (mm) | 3D points | Mean gain |",
           "|---|---|---|---|---|---|---|---|---|"]
    for t in ORDER:
        rs = rows_by_type.get(t)
        if not rs:
            continue
        out.append(f"| {t if t != 'clear' else 'clear air'}{' (' + DESCRIPTIONS[t] + ')' if t in DESCRIPTIONS else ''} | {len(rs)} | {fmt(rs, 'num_registered')} | "
                   f"{fmt(rs, 'num_registered_any_model')} | {fmt(rs, 'num_models')} | "
                   f"{fmt(rs, 'num_accurate')} | {fmt(rs, 'ate_rmse_m', 1, 1000)} | {fmt(rs, 'num_3d_points')} | "
                   f"{fmt(rs, 'mean_gain', 1)} |")
    return "\n".join(out) + "\n"


def errorbar(ax, g, key, label, scale=1.0, **kw):
    xs, ms, lo, hi = [], [], [], []
    for i, t in enumerate(ORDER):
        if t in g:
            m, a, b = (v * scale for v in stat(g[t], key))
            xs.append(i); ms.append(m); lo.append(m - a); hi.append(b - m)
    ax.errorbar(xs, ms, yerr=[lo, hi], marker="o", capsize=3, label=label, **kw)


def main():
    runs = load()
    FIG.mkdir(parents=True, exist_ok=True)
    ref = [r for r in runs if r["stage"] == "reference"]
    main_g = group(runs, stage="main")
    if ref:
        main_g["clear"] = ref
    md = ["# Study v2 results", "",
          "Generated by `make_plots_v2.py` from `results/v2/runs.jsonl`. Values are the mean over seeds, "
          "with (min–max) when runs differ. An *accurate* pose is within 10 cm and 2° of the clear-air "
          "reference after similarity alignment, at a 3 m median standoff unless stated.", ""]
    md.append(table(main_g, "Water-type sweep (SIFT, 3 m standoff)",
                    "Clear air = replicate COLMAP runs on the undegraded images (seeds 1, 2) scored against "
                    "the seed-0 reference: the run-to-run floor."))
    ali = group(runs, stage="aliked")
    if ali:
        md.append(table(ali, "ALIKED + LightGlue (COLMAP 4 built-in), 3 m standoff, seed 0"))
    for d in (1.5, 3.5, 4.0, 4.5, 5.0, 6.0):
        g = group([r for r in runs if r["stage"] in ("standoff", "transition") and r["standoff_m"] == d])
        if g:
            md.append(table(g, f"Standoff {d:g} m (SIFT)"))
    abl = [r for r in runs if r["stage"] == "ablation"]
    if abl:
        md += ["### Colour-correction ablation (SIFT, 3 m)", "",
               "| Water | Correction | n | Largest model /30 | Any model /30 | Accurate poses /30 | ATE RMSE (mm) | 3D points |",
               "|---|---|---|---|---|---|---|---|"]
        for t in WATER_TYPES:
            base = main_g.get(t, [])
            variants = [("none", base)] + [(c, [r for r in abl if r["water_type"] == t and r["correction"] == c])
                                           for c in ("shades_of_gray", "sea_thru_estimated", "sea_thru_oracle")]
            if not any(rs for c, rs in variants[1:]):
                continue
            for c, rs in variants:
                if rs:
                    md.append(f"| {t} | {c} | {len(rs)} | {fmt(rs, 'num_registered')} | {fmt(rs, 'num_registered_any_model')} | {fmt(rs, 'num_accurate')} | "
                              f"{fmt(rs, 'ate_rmse_m', 1, 1000)} | {fmt(rs, 'num_3d_points')} |")
        md.append("")
    sens = [r for r in runs if r["stage"] == "sensitivity"]
    if sens:
        md += ["### Sensitivity: veiling strength and photon budget (SIFT, seed 0)", "",
               "Baseline values: veil x1, full well 5,000 e-. Reference rows are the seed-0 runs of the main/transition stages.", "",
               "| Condition | Optical depth | Veil | Full well (e-) | Largest model /30 | Any model /30 | Sub-models | Accurate /30 | 3D points |",
               "|---|---|---|---|---|---|---|---|---|"]
        base = {("3C", 3.0): "main_3C_3m_sift_none_s0", ("1C", 5.0): "transition_1C_5m_sift_none_s0"}
        by_tag = {r["tag"]: r for r in runs}
        for (w, d), btag in base.items():
            tau = effective_coefficients(Water(w), r=d)["beta_D"][1] * d
            rows = [by_tag[btag]] if btag in by_tag else []
            rows += [r for r in sens if r["water_type"] == w and r["standoff_m"] == d]
            for r in rows:
                md.append(f"| {w} @ {d:g} m | {tau:.2f} | x{r.get('veil_scale', 1.0):g} | {r.get('full_well_e', 5000.0):,.0f} | "
                          f"{r['num_registered']} | {r.get('num_registered_any_model', 'n/a')} | {r.get('num_models', 'n/a')} | "
                          f"{r.get('num_accurate', 0)} | {r['num_3d_points']:,} |")
        md.append("")
    (RES / "summary.md").write_text("\n".join(md))

    # Figure 1: registration and accurate poses vs water type
    fig, ax = plt.subplots(1, 3, figsize=(15, 4))
    errorbar(ax[0], main_g, "num_registered", "registered (SIFT)")
    errorbar(ax[0], main_g, "num_accurate", "accurate poses (SIFT)")
    if ali:
        errorbar(ax[0], ali, "num_accurate", "accurate poses (ALIKED+LightGlue)", linestyle="--")
    ax[0].set_ylim(-1, 31); ax[0].set_ylabel(f"images of {N_IMAGES}")
    errorbar(ax[1], main_g, "ate_rmse_m", "SIFT", scale=1000)
    if ali:
        errorbar(ax[1], ali, "ate_rmse_m", "ALIKED+LightGlue", scale=1000, linestyle="--")
    ax[1].set_yscale("log"); ax[1].set_ylabel("camera ATE RMSE (mm), log scale")
    errorbar(ax[2], main_g, "num_3d_points", "SIFT")
    if ali:
        errorbar(ax[2], ali, "num_3d_points", "ALIKED+LightGlue", linestyle="--")
    ax[2].set_ylabel("reconstructed 3D points"); ax[2].set_ylim(bottom=0)
    ax[2].set_title("Reconstruction density")
    for a in ax:
        a.set_xticks(range(len(ORDER))); a.set_xticklabels(ORDER); a.set_xlabel("Jerlov water type (3 m median standoff)")
        a.grid(alpha=0.3); a.legend(fontsize=8)
    ax[0].set_title("How many cameras survive, and how many are right")
    ax[1].set_title("Pose error vs the clear-air reference")
    fig.tight_layout(); fig.savefig(FIG / "sweep.png", dpi=150); plt.close(fig)

    # Figure 2: standoff
    st = [r for r in runs if r["stage"] in ("standoff", "main", "transition") and r["water_type"] in ("1C", "3C")]
    if any(r["stage"] in ("standoff", "transition") for r in st):
        fig, ax = plt.subplots(figsize=(5.5, 4))
        for t in ("1C", "3C"):
            ds = sorted({r["standoff_m"] for r in st if r["water_type"] == t})
            m = [np.mean([r["num_accurate"] for r in st if r["water_type"] == t and r["standoff_m"] == d]) for d in ds]
            ax.plot(ds, m, marker="o", label=f"{t} ({DESCRIPTIONS[t]})")
        ax.set_xticks([1.5, 3, 4.5, 6])
        ax.set_xlabel("median standoff (m)"); ax.set_ylabel("accurate poses of 30"); ax.set_ylim(-1, 31)
        ax.grid(alpha=0.3); ax.legend(); ax.set_title("Standoff matters as much as water type")
        fig.tight_layout(); fig.savefig(FIG / "standoff.png", dpi=150); plt.close(fig)

    # Figure 2b: every SIFT run against median optical depth (green beta_D x median standoff)
    pts = [r for r in runs if r["features"] == "sift" and r["correction"] == "none" and r["water_type"] != "clear"
           and r["stage"] != "sensitivity"]
    if pts:
        fig, ax = plt.subplots(figsize=(6.5, 4))
        for d, mk in ((1.5, "s"), (3.0, "o"), (3.5, "D"), (4.0, "D"), (4.5, "v"), (5.0, "v"), (6.0, "^")):
            sel = [r for r in pts if r["standoff_m"] == d]
            if not sel:
                continue
            tau = [effective_coefficients(Water(r["water_type"]), r=d)["beta_D"][1] * d for r in sel]
            ax.scatter(tau, [r["num_accurate"] for r in sel], marker=mk, alpha=0.7, label=f"{d:g} m standoff")
            split = [(t, r) for t, r in zip(tau, sel) if r.get("num_models", 1) > 1 and r["correction"] == "none"]
            if split:
                ax.scatter([t for t, _ in split], [r["num_registered_any_model"] for _, r in split], marker=mk,
                           facecolors="none", edgecolors="k", alpha=0.6)
            for r, t in zip(sel, tau):
                if r["seed"] == 0:
                    ax.annotate(r["water_type"], (t, r["num_accurate"]), textcoords="offset points", xytext=(4, 4), fontsize=7)
        ax.axvspan(2.42, 2.68, color="gray", alpha=0.2, label="observed transition")
        ax.set_xlabel("median optical depth  (green beta_D x median scene depth)")
        ax.set_ylabel("accurate poses of 30 (largest model)"); ax.set_ylim(-1, 31); ax.grid(alpha=0.3); ax.legend(fontsize=7)
        ax.set_title("SfM against optical depth (hollow = cameras in any sub-model)", fontsize=10)
        fig.tight_layout(); fig.savefig(FIG / "optical_depth.png", dpi=150); plt.close(fig)

    # Figure 3: ablation
    if abl:
        levels = sorted({r["water_type"] for r in abl}, key=WATER_TYPES.index)
        corrs = ["none", "shades_of_gray", "sea_thru_estimated", "sea_thru_oracle"]
        fig, ax = plt.subplots(figsize=(7, 4))
        w = 0.2
        for j, c in enumerate(corrs):
            vals = []
            for t in levels:
                rs = main_g.get(t, []) if c == "none" else [r for r in abl if r["water_type"] == t and r["correction"] == c]
                vals.append(np.mean([r["num_accurate"] for r in rs]) if rs else np.nan)
            ax.bar(np.arange(len(levels)) + (j - 1.5) * w, vals, w, label=c.replace("_", " "))
        ax.set_xticks(range(len(levels))); ax.set_xticklabels(levels); ax.set_ylabel("accurate poses of 30")
        ax.set_ylim(0, 31); ax.legend(fontsize=8); ax.grid(alpha=0.3, axis="y")
        ax.set_title("Colour correction at the failure region")
        fig.tight_layout(); fig.savefig(FIG / "ablation.png", dpi=150); plt.close(fig)
    print((RES / "summary.md").read_text())


def hero():
    """One frame rendered through every water type at the 3 m standoff (seed 0 images)."""
    tiles = []
    for t in ORDER:
        p = ROOT / "work" / "sets" / (f"main_{t}_3m_sift_none_s0" if t != "clear" else "reference_clear_3m_sift_none_s1") / "P1180150.JPG"
        if p.exists():
            im = cv2.resize(cv2.imread(str(p)), (400, 300), interpolation=cv2.INTER_AREA)
            cv2.putText(im, t, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2, cv2.LINE_AA)
            tiles.append(im)
    if tiles:
        FIG.mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(FIG / "hero.jpg"), np.hstack(tiles), [cv2.IMWRITE_JPEG_QUALITY, 88])


if __name__ == "__main__":
    main()
    hero()
